#!/usr/bin/env bash
# Reproduces T-1, T-2 and T-3 end to end: ESBMC proofs over every offset, native
# witnesses, contract cases against std::stringbuf, reachability, and the
# proposed fix. Run from this directory. Exits 0 only if every leg matches.
#
#   ./reproduce.sh            all five legs
#   ./reproduce.sh esbmc      one leg: esbmc | sanitizer | tests | reachability |
#                             fix
#
# Needs ESBMC 8.4.0 or 8.5.0 (with Z3 and Bitwuzla), a C++11 compiler and curl.

set -u

UPSTREAM_VERSION=$(cat vendor/UPSTREAM_VERSION)
UPSTREAM_COMMIT=$(cat vendor/UPSTREAM_COMMIT)
# A tag can be moved; the commit cannot. REPORT.md pins both, so the re-check
# has to use the one that actually holds.
RAW=https://raw.githubusercontent.com/aws/aws-sdk-cpp/$UPSTREAM_COMMIT
CORE=src/aws-cpp-sdk-core
SIMPLE=vendor/source/utils/stream/SimpleStreamBuf.cpp
PREALLOC=vendor/source/utils/stream/PreallocatedStreamBuf.cpp
# Pins the size of the evidence tree, so a vanished vendor/ fails loudly instead
# of passing a drift check it never ran.
VENDORED_FILES=18
CXX=${CXX:-g++}
INCLUDES="-Istubs -Ivendor/include"
LINK="stubs/aws_memory_stub.cpp stubs/aws_logging_link_stub.cpp"
SAN="-fsanitize=address,undefined -fno-omit-frame-pointer"

# ESBMC's std::basic_streambuf declares the get and put areas without defining
# them, so the leg below analyses the five functions under test cut out of the
# pristine files at run time, against the stand-in base in stubs/esbmc/. See
# README.md "Why a slice"; `slice` is the only thing that produces one and it
# never edits a line of what it cuts.
ESBMC_FLAGS="--std c++11 -D ESBMC_OM_MISSING_STREAMPOS -Istubs/esbmc --unwind 4"

pass=0 fail=0 skip=0
# A leg that cannot run has not matched, so it must not leave the run exiting 0.
# Same reasoning as VENDORED_FILES above: absence of evidence has to be loud.
skip() { printf '  SKIP  %s\n' "$1"; skip=$((skip + 1)); }
check() { # check <name> <expected-substring> <actual>
  if [[ "$3" == *"$2"* ]]; then printf '  PASS  %s\n' "$1"; pass=$((pass + 1))
  else printf '  FAIL  %s\n        wanted: %s\n        got: %s\n' "$1" "$2" "$3"; fail=$((fail + 1)); fi
}

# Match the verdict line itself rather than a tail window: the version banner
# arrives on the other stream, and a run that produces no verdict at all should
# say so instead of failing as a wrong one.
verdict() {
  local out; out=$("$@" 2>&1)
  grep -m1 -E '^VERIFICATION (SUCCESSFUL|FAILED)' <<<"$out" ||
    printf 'no verdict; last lines: %s' "$(tail -3 <<<"$out" | tr '\n' ' ')"
}

# A build that fails has to be a failure, not a leg that quietly stops: bare
# `|| return` leaves the totals reading "N passed, 0 failed" and exits 0.
build() { # build <output> <source...> -- <flags...>
  local out=$1; shift
  $CXX -std=c++11 -g -O1 $INCLUDES "$@" -o "$out" && return 0
  printf '  FAIL  build %s\n' "$out"; fail=$((fail + 1)); return 1
}

# Counting diagnostics rather than matching an empty string: an empty
# expectation matches anything. Callers must pass output they captured from a
# run that also produced a checked answer -- `grep -c` prints 0 for no input,
# so silence alone cannot tell "clean" from "never ran".
san_count() { grep -cE 'runtime error|ERROR: AddressSanitizer' <<<"$1"; }

# Cuts one function definition out of a file: from the line the pattern matches
# to the line its brace count returns to zero. Brace counting rather than a
# closing-brace-at-column-zero pattern, because PreallocatedStreamBuf.cpp indents
# its definitions four namespaces deep.
cut_function() { # cut_function <file> <regex>
  awk -v pat="$2" '
    $0 ~ pat && !inside { inside = 1; depth = 0; started = 0 }
    inside {
      print
      depth += gsub(/\{/, "{") - gsub(/\}/, "}")
      if (depth > 0) started = 1
      if (started && depth == 0) { inside = 0; started = 0; print "" }
    }' "$1"
}

slice() { # slice <simple-source> <prealloc-source> <destination>
  { cat <<'EOF'
/* GENERATED by reproduce.sh -- every line below the namespace opener is cut
 * verbatim from the pristine source named above its block. Do not edit. */
#include <cassert>
/* underflow() names std::char_traits<char>, which ESBMC 8.4.0's <streambuf>
 * only forward-declares; <string> carries the definition. Harmless on 8.5.0,
 * where <streambuf> is enough, and it is what lets both versions read the same
 * bytes. */
#include <string>

#include "streambuf_scaffold.h"

namespace Aws { namespace Utils { namespace Stream {

EOF
    printf '/* %s */\n' "$1"
    cut_function "$1" '^std::streampos SimpleStreamBuf::seekoff'
    cut_function "$1" '^std::streampos SimpleStreamBuf::seekpos'
    cut_function "$1" '^int SimpleStreamBuf::underflow'
    printf '/* %s */\n' "$2"
    cut_function "$2" 'PreallocatedStreamBuf::PreallocatedStreamBuf'
    cut_function "$2" 'PreallocatedStreamBuf::seekoff'
    cut_function "$2" 'PreallocatedStreamBuf::seekpos'
    echo '}}}'
  } > "$3"
}

esbmc_run() { # esbmc_run <solver> <source> [defines...]
  local solver=$1 src=$2; shift 2
  verdict esbmc $ESBMC_FLAGS "$solver" "$@" harnesses/streambuf_esbmc.cpp "$src"
}

both_solvers() { # both_solvers <name> <expected> <source> [defines...]
  local name=$1 want=$2 src=$3; shift 3
  check "$name (Bitwuzla)" "$want" "$(esbmc_run --bitwuzla "$src" "$@")"
  check "$name (Z3)"       "$want" "$(esbmc_run --z3       "$src" "$@")"
}

# FAILED alone does not say what failed: a run that stops at an unrelated
# memory-safety check prints the same verdict as one that reached the property.
# This lists every violated claim -- all of them, since a debug run breaks the
# module's own assert as well as the harness's -- so a row cannot pass for the
# wrong reason. Empty output fails any non-empty expectation, so a run that
# produced no listing at all cannot read as a match either.
violations() { # violations <source> [defines...]
  local src=$1; shift
  esbmc $ESBMC_FLAGS --bitwuzla "$@" harnesses/streambuf_esbmc.cpp "$src" 2>&1 |
    grep -E '^ +FAILED ' || echo "no violated property reported"
}

leg_esbmc() {
  echo "[1/5] ESBMC -- every seek offset, over the pristine arithmetic"
  command -v esbmc >/dev/null || { skip "esbmc not on PATH"; return; }
  mkdir -p results
  slice "$SIMPLE" "$PREALLOC" results/streambuf_pristine.cpp

  # The property is not trivially false: off == 0, the one end-relative seek the
  # SDK's own callers perform, is also the one a sign error cannot reach.
  both_solvers "control: seekg(0,end) lands where it should" "VERIFICATION SUCCESSFUL" \
    results/streambuf_pristine.cpp -D NDEBUG -D HARNESS_MODE_SEEK_ZERO

  both_solvers "end-relative seeks do not land at length + off" "VERIFICATION FAILED" \
    results/streambuf_pristine.cpp -D NDEBUG
  both_solvers "a backward seek lands somewhere else"          "VERIFICATION FAILED" \
    results/streambuf_pristine.cpp -D NDEBUG -D HARNESS_MODE_SEEK_BACK
  both_solvers "and aborts outright with the asserts live"     "VERIFICATION FAILED" \
    results/streambuf_pristine.cpp -D HARNESS_MODE_SEEK_BACK
  both_solvers "an in|out seek reports success having moved nothing" "VERIFICATION FAILED" \
    results/streambuf_pristine.cpp -D NDEBUG -D HARNESS_MODE_SEEK_BOTH
  both_solvers "underflow puts gptr past egptr"                "VERIFICATION FAILED" \
    results/streambuf_pristine.cpp -D NDEBUG -D HARNESS_MODE_GET_AREA
  both_solvers "the transfer manager's buffer seeks the same way" "VERIFICATION FAILED" \
    results/streambuf_pristine.cpp -D NDEBUG -D HARNESS_MODE_PREALLOC_END
  both_solvers "and reports the same empty success"            "VERIFICATION FAILED" \
    results/streambuf_pristine.cpp -D NDEBUG -D HARNESS_MODE_PREALLOC_BOTH

  # Which claim each verdict above broke.
  local P=results/streambuf_pristine.cpp
  check "the end-relative row broke the landing property" \
    "an end-relative seek outside the sequence reported success" \
    "$(violations $P -D NDEBUG)"
  check "the backward row broke it too" \
    "an end-relative seek inside the sequence did not land at length + off" \
    "$(violations $P -D NDEBUG -D HARNESS_MODE_SEEK_BACK)"
  check "the in|out row broke the positioning property" \
    "a seek that reported success did not position both sequences" \
    "$(violations $P -D NDEBUG -D HARNESS_MODE_SEEK_BOTH)"
  check "the underflow row broke the get-area property" \
    "underflow left the get area with gptr past egptr" \
    "$(violations $P -D NDEBUG -D HARNESS_MODE_GET_AREA)"
  check "the upload buffer broke the same landing property" \
    "an end-relative seek outside the sequence reported success" \
    "$(violations $P -D NDEBUG -D HARNESS_MODE_PREALLOC_END)"
  check "and the upload buffer's in|out row broke the positioning one" \
    "a seek that reported success did not position both sequences" \
    "$(violations $P -D NDEBUG -D HARNESS_MODE_PREALLOC_BOTH)"
  # And the debug row, which stops earlier than any of them: at the module's own
  # assert rather than at a property of ours.
  check "the abort is SimpleStreamBuf's own assert" \
    "assertion static_cast<size_t>(pos) <= maxSeek" \
    "$(violations $P -D HARNESS_MODE_SEEK_BACK)"
}

leg_sanitizer() {
  echo "[2/5] Sanitizers -- T-1 from a public sequence, one behaviour per process"
  mkdir -p results
  local module="$SIMPLE $PREALLOC $LINK"
  build results/witness_ndebug -DNDEBUG $SAN harnesses/streambuf_witness.cpp $module || return
  build results/witness_debug           $SAN harnesses/streambuf_witness.cpp $module || return
  build results/witness_plain  -DNDEBUG      harnesses/streambuf_witness.cpp $module || return

  # The control: the same sequence on the buffer SimpleStreamBuf replaces.
  local reference; reference=$(./results/witness_ndebug reference 2>&1)
  check "std::stringbuf reads the written bytes and stops" "on the same sequence: gcount=10" "$reference"
  check "and reads nothing after the write"                "ending in a write: gcount=0" "$reference"
  # The control's cleanliness is the point of it, so it is counted from the same
  # run rather than printed by the program under observation.
  check "with both sanitizers silent on the control"       "diagnostics=0" "diagnostics=$(san_count "$reference")"

  local invariant; invariant=$(./results/witness_ndebug invariant 2>&1)
  check "underflow leaves gptr past egptr"        "gptr=51 egptr=10" "$invariant"
  check "which is a get area no read can use"     "get area well-formed, gptr <= egptr: no" "$invariant"
  check "a one-byte read returns unwritten heap"  "which the application never wrote" \
    "$(./results/witness_ndebug stale 2>&1)"

  # The size is the whole finding: memcpy takes size_t, so egptr() - gptr()
  # arriving negative is a copy of ~2^64 bytes, not a short one.
  check "a longer read memcpys a negative length" "negative-size-param: (size=-41)" \
    "$(./results/witness_ndebug crash 2>&1)"
  check "the asserts do not stand in the way"     "negative-size-param: (size=-41)" \
    "$(./results/witness_debug crash 2>&1)"

  # The second site. underflow is not the only place this class hands setg an
  # unchecked pptr(): xsputn does it too (:197), so ending the same sequence
  # with a write reaches the inversion without underflow running at all.
  local write; write=$(./results/witness_ndebug write 2>&1)
  check "a write inverts the get area the same way" "gptr=50 egptr=15" "$write"
  check "and the read after it memcpys a negative length" "negative-size-param: (size=-35)" "$write"

  # Without a sanitizer to stop it: an ordinary release build dies here, so the
  # diagnostic above is not the instrumentation inventing a problem.
  # In a subshell so bash reports the signal here rather than printing its own
  # "Segmentation fault" line over the leg's output.
  local signal; (./results/witness_plain crash >/dev/null 2>&1); signal=$?
  check "an uninstrumented build takes SIGSEGV" "139" "$signal"

  # Tie the silence elsewhere to a run that demonstrably did the work.
  local clean; clean=$(./results/witness_ndebug invariant 2>&1)
  check "nothing else is flagged on the way there" "diagnostics=0" \
    "diagnostics=$(san_count "$clean")"
}

leg_tests() {
  echo "[3/5] Contract cases -- both buffers beside the one they replace"
  mkdir -p results
  build results/cases_pristine -DNDEBUG harnesses/streambuf_cases.cpp \
        "$SIMPLE" "$PREALLOC" $LINK || return
  local out; out=$(./results/cases_pristine)

  # The control first: every row is a row std::stringbuf passes, so a failure
  # below is a disagreement with the standard rather than an invented rule.
  check "the reference buffer passes every row" "0 of 7 reference cases failed" "$out"
  check "SimpleStreamBuf fails four"            "4 of 7 SimpleStreamBuf cases failed" "$out"
  check "PreallocatedStreamBuf fails the same four" "4 of 7 PreallocatedStreamBuf cases failed" "$out"

  # Name which rows, not just how many: a patch that broke ordinary seeking
  # would also produce four failures.
  check "seeking to the last bytes fails"      "FAIL  simple     7" "$out"
  check "seeking past the end succeeds"        "FAIL  simple     FAIL           got 7" "$out"
  check "and the same on the upload buffer"    "FAIL  prealloc   7" "$out"
  check "ordinary seeking is untouched"        "PASS  simple     5" "$out"
}

leg_reachability() {
  echo "[4/5] Reachability -- the vendored bytes, and who reaches these buffers"
  local tmp; tmp=$(mktemp -d)
  curl -fsS "$RAW/$CORE/source/http/curl/CurlHttpClient.cpp" -o "$tmp/Curl.cpp" 2>/dev/null \
    || { skip "no network"; rm -rf "$tmp"; return; }
  curl -fsS "$RAW/src/aws-cpp-sdk-transfer/source/transfer/TransferManager.cpp" -o "$tmp/Transfer.cpp"
  curl -fsS "$RAW/$CORE/include/aws/core/utils/memory/stl/AWSStringStream.h" -o "$tmp/StringStream.h"

  # The whole vendored tree, not just the two modules: REPORT.md cites headers
  # by line too. Names what drifted, since "differs" alone would not say where.
  local drift="" vendored=0
  while read -r rel; do
    vendored=$((vendored + 1))
    curl -fsS "$RAW/$CORE/$rel" -o "$tmp/upstream" 2>/dev/null &&
      diff -q "$tmp/upstream" "vendor/$rel" >/dev/null || drift="$drift $rel"
  done < <(cd vendor && find include source -type f | sort)
  # The count is asserted, not just printed: an empty vendor tree would leave
  # `drift` empty too and otherwise read as a clean pass.
  check "all $VENDORED_FILES vendored files are upstream $UPSTREAM_VERSION" \
    "$VENDORED_FILES files, no drift" "$vendored files,${drift:- no drift}"

  # stubs/ precedes vendor/include on the include path, so a stub named after a
  # pinned header would silently replace the evidence -- and the drift check
  # above, which compares vendor/ to upstream, would still report no drift.
  check "no stub shadows a vendored header" "none" \
    "$(comm -12 <(cd stubs && find . -name '*.h' | sed 's|^\./||' | sort) \
                <(cd vendor/include && find . -name '*.h' | sed 's|^\./||' | sort) |
       tr '\n' ' ' | grep . || echo none)"

  # PreallocatedStreamBuf carries every multipart upload part, and the curl
  # client hands whatever libcurl asks for straight to the stream. See
  # REPORT.md "Reachability" for the enumeration these three rows check.
  check "the transfer manager wraps each part in one" "PreallocatedStreamBuf>(CLASS_TAG, buffer" \
    "$(grep -m1 'Aws::New<Aws::Utils::Stream::PreallocatedStreamBuf>' "$tmp/Transfer.cpp")"
  check "the curl client forwards SEEK_END as ios_base::end" "dir = std::ios_base::end;" \
    "$(grep -A1 -m1 'case SEEK_END:' "$tmp/Curl.cpp")"
  check "and seeks the body with it" "ioStream->seekg(offset, dir);" \
    "$(grep -m1 'ioStream->seekg' "$tmp/Curl.cpp")"

  # SimpleStreamBuf is public exported API everywhere, but the SDK wires it in
  # only on this configuration. The report says so; this is where it is checked.
  check "SimpleStreamBuf backs Aws::StringStream only on Android gnustl" \
    "_GLIBCXX_FULLY_DYNAMIC_STRING == 0 && defined(__ANDROID__)" \
    "$(grep -m1 'FULLY_DYNAMIC_STRING' "$tmp/StringStream.h")"
  rm -rf "$tmp"
}

leg_fix() {
  echo "[5/5] Fix -- fix/streambuf-seek-and-get-area.patch closes every property"
  mkdir -p results
  # The patch names the two files by their upstream paths, so it is applied to a
  # tree that has those paths rather than to each copy in turn.
  local tree=results/fixed/$CORE/source/utils/stream
  rm -rf results/fixed; mkdir -p "$tree"
  cp "$SIMPLE" "$PREALLOC" "$tree"
  patch -s -p1 -d results/fixed --no-backup-if-mismatch \
        --input="$PWD/fix/streambuf-seek-and-get-area.patch" ||
    { echo "  FAIL  patch does not apply"; fail=$((fail + 1)); return; }
  local simple_fixed=$tree/SimpleStreamBuf.cpp
  local prealloc_fixed=$tree/PreallocatedStreamBuf.cpp

  build results/cases_fixed -DNDEBUG harnesses/streambuf_cases.cpp \
        "$simple_fixed" "$prealloc_fixed" $LINK || return
  local out; out=$(./results/cases_fixed)
  check "every SimpleStreamBuf row passes"      "0 of 7 SimpleStreamBuf cases failed" "$out"
  check "every PreallocatedStreamBuf row passes" "0 of 7 PreallocatedStreamBuf cases failed" "$out"
  check "the reference is still the reference"  "0 of 7 reference cases failed" "$out"

  build results/witness_fixed -DNDEBUG $SAN harnesses/streambuf_witness.cpp \
        "$simple_fixed" "$prealloc_fixed" $LINK || return
  local invariant; invariant=$(./results/witness_fixed invariant 2>&1)
  check "underflow keeps the get area well-formed" "get area well-formed, gptr <= egptr: yes" "$invariant"
  check "a read past the written data stops"  "reported EOF" \
    "$(./results/witness_fixed stale 2>&1)"
  # The same read the pristine build died on, and the same answer the reference
  # gives: 10 bytes, which is what was written after the put pointer moved back.
  local crash; crash=$(./results/witness_fixed crash 2>&1)
  check "the negative memcpy is gone"         "gcount=10" "$crash"
  check "with both sanitizers silent"         "diagnostics=0" "diagnostics=$(san_count "$crash")"

  # Both sites, not just underflow's: the write path has its own hunk, and its
  # answer is std::stringbuf's -- nothing left to read, and no diagnostic.
  local write; write=$(./results/witness_fixed write 2>&1)
  check "the write path keeps it well-formed too" "get area well-formed, gptr <= egptr: yes" "$write"
  check "and reads nothing after it, as the reference does" "gcount=0" "$write"
  check "with both sanitizers silent there too" "diagnostics=0" "diagnostics=$(san_count "$write")"

  command -v esbmc >/dev/null || { skip "esbmc not on PATH"; return; }
  slice "$simple_fixed" "$prealloc_fixed" results/streambuf_fixed.cpp
  both_solvers "end-relative seeks land at length + off" "VERIFICATION SUCCESSFUL" \
    results/streambuf_fixed.cpp -D NDEBUG
  both_solvers "backward seeks land, asserts live"       "VERIFICATION SUCCESSFUL" \
    results/streambuf_fixed.cpp -D HARNESS_MODE_SEEK_BACK
  both_solvers "an in|out seek positions both sequences" "VERIFICATION SUCCESSFUL" \
    results/streambuf_fixed.cpp -D NDEBUG -D HARNESS_MODE_SEEK_BOTH
  both_solvers "underflow keeps the get area well formed" "VERIFICATION SUCCESSFUL" \
    results/streambuf_fixed.cpp -D NDEBUG -D HARNESS_MODE_GET_AREA
  both_solvers "the upload buffer seeks correctly"       "VERIFICATION SUCCESSFUL" \
    results/streambuf_fixed.cpp -D NDEBUG -D HARNESS_MODE_PREALLOC_END
  both_solvers "and positions both sequences"            "VERIFICATION SUCCESSFUL" \
    results/streambuf_fixed.cpp -D NDEBUG -D HARNESS_MODE_PREALLOC_BOTH

  # What the patch deliberately leaves alone. seekpos asserts that its caller
  # never asks for a position outside the sequence, but returning -1 is how the
  # API is required to say no, so a debug build still aborts where a release
  # build fails gracefully. Pre-existing, unchanged by the patch, and reported
  # under T-2 rather than fixed here. See REPORT.md "What the patch does not do".
  both_solvers "an out-of-range seek still aborts a debug build" "VERIFICATION FAILED" \
    results/streambuf_fixed.cpp
  # The only FAILED row in this leg, so name the claim it broke: it must be the
  # module's own assert and not a property the patch was supposed to close.
  check "and it is the module's own assert that stops it" \
    "assertion static_cast<size_t>(pos) <= maxSeek" \
    "$(violations results/streambuf_fixed.cpp)"
}

case "${1:-all}" in
  esbmc)        leg_esbmc ;;
  sanitizer)    leg_sanitizer ;;
  tests)        leg_tests ;;
  reachability) leg_reachability ;;
  fix)          leg_fix ;;
  all)          leg_esbmc; leg_sanitizer; leg_tests; leg_reachability; leg_fix ;;
  *)            echo "usage: $0 [all|esbmc|sanitizer|tests|reachability|fix]"; exit 2 ;;
esac

printf '\n%d passed, %d failed' "$pass" "$fail"
[[ $skip -eq 0 ]] && printf '\n' || printf ', %d skipped -- the run proves less than it reads\n' "$skip"
[[ $fail -eq 0 && $skip -eq 0 ]]
