#!/usr/bin/env bash
# Reproduces H-1 end to end: ESBMC proofs, native witnesses, contract cases,
# reachability, and the proposed fix. Run from this directory. Exits 0 only if
# every leg matches.
#
#   ./reproduce.sh            all five legs
#   ./reproduce.sh esbmc      one leg: esbmc | sanitizer | tests | reachability | fix
#
# Needs ESBMC 8.4.0 (with Z3 and Bitwuzla), a C++11 compiler and curl.

set -u

UPSTREAM_VERSION=$(cat vendor/UPSTREAM_VERSION)
UPSTREAM_COMMIT=$(cat vendor/UPSTREAM_COMMIT)
RAW=https://raw.githubusercontent.com/aws/aws-sdk-cpp/$UPSTREAM_VERSION
CORE=src/aws-cpp-sdk-core
MODULE=vendor/source/utils/HashingUtils.cpp
CXX=${CXX:-g++}
INCLUDES="-Istubs -Ivendor -Ivendor/include"
LINK="vendor/source/utils/base64/Base64.cpp stubs/aws_crypto_link_stub.cpp stubs/aws_memory_stub.cpp"

# ESBMC cannot parse the whole translation unit yet -- three operational-model
# gaps, listed in README.md "Why a slice". Both legs below therefore analyse a
# slice cut out of the pristine file at run time, never a hand-written copy;
# `slice` is the only thing that produces one and it never edits a line.
ESBMC_FLAGS="--std c++11 -D ESBMC_OM_MISSING_ALLOCATE_SHARED
             -Istubs/esbmc $INCLUDES --force-malloc-success --unwind 16"

pass=0 fail=0
check() { # check <name> <expected-substring> <actual>
  if [[ "$3" == *"$2"* ]]; then printf '  PASS  %s\n' "$1"; pass=$((pass + 1))
  else printf '  FAIL  %s\n        wanted: %s\n        got: %s\n' "$1" "$2" "$3"; fail=$((fail + 1)); fi
}

# Match the verdict line itself rather than a tail window: the version banner
# arrives on the other stream, and a run that produces no verdict at all should
# say so instead of failing as a wrong one.
verdict() {
  local out; out=$("$@" 2>&1)
  grep -m1 -E '^VERIFICATION (SUCCESSFUL|FAILED)' <<<"$out" ||
    printf 'no verdict; last lines: %s' "$(tail -3 <<<"$out" | tr '\n' ' ')"
}

slice() { # slice <source> <destination>
  { cat <<'EOF'
/* GENERATED by reproduce.sh -- bytes below are cut verbatim from the file named
 * on the next line. Do not edit; regenerate. */
EOF
    printf '/* source: %s */\n\n' "$1"
    cat <<'EOF'
#include <aws/core/utils/HashingUtils.h>
#include <aws/core/utils/StringUtils.h>

#include <cassert>
#include <cctype>

using namespace Aws::Utils;

EOF
    awk '/^static bool IsHexDigit|^ByteBuffer HashingUtils::HexDecode/,/^}$/' "$1"
  } > "$2"
}

esbmc_run() { # esbmc_run <solver> <source> [defines...]
  local solver=$1 src=$2; shift 2
  verdict esbmc "$solver" $ESBMC_FLAGS "$@" harnesses/hex_decode_esbmc.cpp "$src" stubs/aws_memory_stub.cpp
}

both_solvers() { # both_solvers <name> <expected> <source> [defines...]
  local name=$1 want=$2 src=$3; shift 3
  check "$name (Bitwuzla)" "$want" "$(esbmc_run --bitwuzla "$src" "$@")"
  check "$name (Z3)"       "$want" "$(esbmc_run --z3       "$src" "$@")"
}

leg_esbmc() {
  echo "[1/5] ESBMC -- what HexDecode accepts, over bytes sliced from the pristine file"
  command -v esbmc >/dev/null || { echo "  SKIP  esbmc not on PATH"; return; }
  mkdir -p results
  slice "$MODULE" results/hexdecode_pristine.cpp

  # The property is not trivially false: a well-formed argument verifies.
  both_solvers "control: hex input verifies" "VERIFICATION SUCCESSFUL" \
    results/hexdecode_pristine.cpp -D NDEBUG -D HARNESS_MODE_HEX_ONLY

  # Alnum input, asserts LIVE. IsAlnum passes 'g'-'z' and 'G'-'Z', so this
  # violation does not need NDEBUG: a debug build accepts them too.
  both_solvers "non-hex letters accepted with asserts live" "VERIFICATION FAILED" \
    results/hexdecode_pristine.cpp
  both_solvers "non-hex letters accepted under NDEBUG" "VERIFICATION FAILED" \
    results/hexdecode_pristine.cpp -D NDEBUG
  both_solvers "any byte accepted under NDEBUG" "VERIFICATION FAILED" \
    results/hexdecode_pristine.cpp -D NDEBUG -D HARNESS_MODE_ANY_BYTE
  both_solvers "high-bit bytes accepted under NDEBUG" "VERIFICATION FAILED" \
    results/hexdecode_pristine.cpp -D NDEBUG -D HARNESS_MODE_HIGH_BIT

  # The headline: a string a caller would reject decodes to the bytes of one it
  # would accept. Asserts live again -- the witness is alnum.
  both_solvers "a non-hex string aliases a hex one" "VERIFICATION FAILED" \
    results/hexdecode_pristine.cpp -D HARNESS_MODE_ALIAS
}

leg_sanitizer() {
  echo "[2/5] Sanitizers -- the whole pristine module, one input per process"
  mkdir -p results
  local san="-fsanitize=address,undefined -fno-omit-frame-pointer"
  $CXX -std=c++11 -g -O1 -DNDEBUG $san $INCLUDES harnesses/hex_decode_witness.cpp \
       "$MODULE" $LINK -o results/witness_release || return
  $CXX -std=c++11 -g -O1 $san $INCLUDES harnesses/hex_decode_witness.cpp \
       "$MODULE" $LINK -o results/witness_debug || return

  check "\"K1\" decodes to the byte \"41\" decodes to" "decoded=1 bytes: 41" \
    "$(./results/witness_release K1 2>&1)"
  check "\"EW\" decodes to 0x00"                       "decoded=1 bytes: 00" \
    "$(./results/witness_release EW 2>&1)"
  check "a high-bit byte decodes under NDEBUG"         "decoded=1 bytes: 50" \
    "$(./results/witness_release '\x80\x80' 2>&1)"
  # An empty expectation would match anything, so count the diagnostics and
  # compare the count.
  check "ASan and UBSan stay clean on all of it"       "diagnostics=0" \
    "diagnostics=$(./results/witness_release K1 EW zz v0 0x41 2>&1 |
                   grep -cE 'runtime error|ERROR: AddressSanitizer')"

  # Only the non-alnum byte reaches the assert; the letters never do.
  check "a debug build accepts \"K1\" too"             "decoded=1 bytes: 41" \
    "$(./results/witness_debug K1 2>&1)"
  check "a debug build stops at the high-bit byte"     "Assertion \`0' failed" \
    "$(./results/witness_debug '\x80\x80' 2>&1)"

  # C17 7.4p1: neither sanitizer checks the ctype precondition, so watch the
  # call itself. Against an uninstrumented build -- ASan insists on being first
  # in the preload list and refuses to run behind another interposer.
  $CXX -std=c++11 -g -O1 -DNDEBUG $INCLUDES harnesses/hex_decode_witness.cpp \
       "$MODULE" $LINK -o results/witness_plain || return
  gcc -std=c99 -shared -fPIC -O1 stubs/ctype_precondition_guard.c -o results/ctype_guard.so || return
  check "isalpha is called with a negative char"       "isalpha(-128)" \
    "$(LD_PRELOAD=$PWD/results/ctype_guard.so ./results/witness_plain '\x80\x80' 2>&1)"
  check "well-formed input keeps the precondition"     "decoded=1 bytes: 41" \
    "$(LD_PRELOAD=$PWD/results/ctype_guard.so ./results/witness_plain 41 2>&1)"
}

leg_tests() {
  echo "[3/5] Contract cases -- ordinary release build, wrong values visible"
  mkdir -p results
  $CXX -std=c++11 -g -O1 -DNDEBUG $INCLUDES harnesses/hex_decode_cases.cpp \
       "$MODULE" $LINK -o results/cases_pristine || return
  local out; out=$(./results/cases_pristine)
  check "the five well-formed cases pass"  "PASS  41"                      "$out"
  check "the eight H-1 cases fail"         "8 of 13 contract cases failed" "$out"

  # The census: how wide the acceptance and the aliasing actually are.
  $CXX -std=c++11 -g -O1 -DNDEBUG $INCLUDES harnesses/hex_decode_witness.cpp \
       "$MODULE" $LINK -o results/witness_plain || return
  local census; census=$(./results/witness_plain | tr -s ' ')
  check "3844 two-character strings admitted" "guard admits : 3844"   "$census"
  check "3360 of them are not hex"            "not hex : 3360"        "$census"
  check "every byte value has a preimage"     "values produced : 256" "$census"
  check "the largest preimage is 25 strings"  "preimage : 25 strings" "$census"
}

leg_reachability() {
  echo "[4/5] Reachability -- who calls HexDecode at $UPSTREAM_VERSION"
  local tmp; tmp=$(mktemp -d)
  curl -fsS "$RAW/$CORE/source/utils/UUID.cpp" -o "$tmp/UUID.cpp" 2>/dev/null \
    || { echo "  SKIP  no network"; rm -rf "$tmp"; return; }
  curl -fsS "$RAW/$CORE/source/auth/signer/AWSAuthV4Signer.cpp" -o "$tmp/Signer.cpp"

  # The vendored module has to be the shipped one for anything above to count.
  curl -fsS "$RAW/$CORE/source/utils/HashingUtils.cpp" -o "$tmp/HashingUtils.cpp"
  check "vendored module is upstream $UPSTREAM_VERSION" "identical" \
    "$(diff -q "$tmp/HashingUtils.cpp" "$MODULE" >/dev/null && echo identical || echo differs)"

  # Two non-test call sites in the whole repository, both feeding HexDecode
  # something the SDK produced itself. See REPORT.md "Reachability" for the
  # enumeration this checks.
  check "UUID's string ctor decodes its argument" "HexDecode(escapedHexStr)" \
    "$(grep -m1 HexDecode "$tmp/UUID.cpp")"
  check "the signer decodes its own payload hash" "HexDecode(payloadHash)" \
    "$(grep -m1 HexDecode "$tmp/Signer.cpp")"
  check "that hash is HexEncode of a local digest" "HexEncode(sha256Digest)" \
    "$(grep -m1 'payloadHash(HashingUtils::HexEncode' "$tmp/Signer.cpp")"
  rm -rf "$tmp"
}

leg_fix() {
  echo "[5/5] Fix -- fix/h1-reject-non-hex.patch closes every property above"
  mkdir -p results
  local fixed=results/HashingUtils.fixed.cpp
  cp "$MODULE" "$fixed"
  patch -s -p1 --no-backup-if-mismatch --input=fix/h1-reject-non-hex.patch "$fixed" \
    || { echo "  FAIL  patch does not apply"; fail=$((fail + 1)); return; }

  $CXX -std=c++11 -g -O1 -DNDEBUG $INCLUDES harnesses/hex_decode_cases.cpp \
       "$fixed" $LINK -o results/cases_fixed || return
  check "every contract case passes" "0 of 13 contract cases failed" "$(./results/cases_fixed)"

  command -v esbmc >/dev/null || { echo "  SKIP  esbmc not on PATH"; return; }
  slice "$fixed" results/hexdecode_fixed.cpp
  both_solvers "non-hex input no longer decodes" "VERIFICATION SUCCESSFUL" \
    results/hexdecode_fixed.cpp -D NDEBUG
  both_solvers "no byte value decodes"           "VERIFICATION SUCCESSFUL" \
    results/hexdecode_fixed.cpp -D NDEBUG -D HARNESS_MODE_ANY_BYTE
  both_solvers "the aliasing is gone"            "VERIFICATION SUCCESSFUL" \
    results/hexdecode_fixed.cpp -D NDEBUG -D HARNESS_MODE_ALIAS
}

case "${1:-all}" in
  esbmc)        leg_esbmc ;;
  sanitizer)    leg_sanitizer ;;
  tests)        leg_tests ;;
  reachability) leg_reachability ;;
  fix)          leg_fix ;;
  all)          leg_esbmc; leg_sanitizer; leg_tests; leg_reachability; leg_fix ;;
  *)            echo "usage: $0 [all|esbmc|sanitizer|tests|reachability|fix]"; exit 2 ;;
esac

printf '\n%d passed, %d failed\n' "$pass" "$fail"
[[ $fail -eq 0 ]]
